import { User, Course, Enrollment, Session, AttendanceRecord } from './types';

export const INITIAL_USERS: User[] = [
  {
    id: 'admin-1',
    name: 'Engr. Dr. Kayode (HOD)',
    email: 'hod.cs@fedpolyado.edu.ng',
    role: 'ADMIN',
    department: 'Software & Web Development',
    institution: 'Federal Polytechnic, Ado-Ekiti',
  },
  {
    id: 'lec-1',
    name: 'Mrs. Abiodun',
    email: 'abiodun@fedpolyado.edu.ng',
    role: 'LECTURER',
    department: 'Software & Web Development',
    institution: 'Federal Polytechnic, Ado-Ekiti',
  },
  {
    id: 'lec-2',
    name: 'Dr. O. Babatunde',
    email: 'babatunde@fedpolyado.edu.ng',
    role: 'LECTURER',
    department: 'Computer Science',
    institution: 'Federal Polytechnic, Ado-Ekiti',
  },
  {
    id: 'stu-1',
    name: 'Sanya Ololade Timileyin',
    email: 'sanya.ololade@student.fedpolyado.edu.ng',
    matricNumber: 'FPA/CS/24/03-0108',
    role: 'STUDENT',
    department: 'Software & Web Development',
    institution: 'Federal Polytechnic, Ado-Ekiti',
  },
  {
    id: 'stu-2',
    name: 'Adewale Segun',
    email: 'adewale.segun@student.fedpolyado.edu.ng',
    matricNumber: 'FPA/CS/24/03-0112',
    role: 'STUDENT',
    department: 'Software & Web Development',
    institution: 'Federal Polytechnic, Ado-Ekiti',
  },
  {
    id: 'stu-3',
    name: 'Chioma Okafor',
    email: 'chioma.okafor@student.fedpolyado.edu.ng',
    matricNumber: 'FPA/CS/24/03-0145',
    role: 'STUDENT',
    department: 'Software & Web Development',
    institution: 'Federal Polytechnic, Ado-Ekiti',
  },
  {
    id: 'stu-4',
    name: 'Ibrahim Musa',
    email: 'ibrahim.musa@student.fedpolyado.edu.ng',
    matricNumber: 'FPA/CS/24/03-0160',
    role: 'STUDENT',
    department: 'Software & Web Development',
    institution: 'Federal Polytechnic, Ado-Ekiti',
  },
];

export const INITIAL_COURSES: Course[] = [
  {
    id: 'course-1',
    code: 'CSC 301',
    title: 'Advanced Web Development & Cloud Systems',
    lecturerId: 'lec-1',
    lecturerName: 'Mrs. Abiodun',
    department: 'Software & Web Development',
    semester: '1st Semester 2025/2026',
    units: 3,
    requiresApproval: false,
    createdAt: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 'course-2',
    code: 'CSC 305',
    title: 'Database Management Systems & SQL',
    lecturerId: 'lec-2',
    lecturerName: 'Dr. O. Babatunde',
    department: 'Computer Science',
    semester: '1st Semester 2025/2026',
    units: 3,
    requiresApproval: true,
    createdAt: '2026-09-02T09:30:00.000Z',
  },
  {
    id: 'course-3',
    code: 'CSC 309',
    title: 'Computer Security & Cryptography',
    lecturerId: 'lec-1',
    lecturerName: 'Mrs. Abiodun',
    department: 'Software & Web Development',
    semester: '1st Semester 2025/2026',
    units: 2,
    requiresApproval: false,
    createdAt: '2026-09-03T10:00:00.000Z',
  },
  {
    id: 'course-4',
    code: 'CSC 313',
    title: 'Mobile Application Architecture',
    lecturerId: 'lec-1',
    lecturerName: 'Mrs. Abiodun',
    department: 'Software & Web Development',
    semester: '1st Semester 2025/2026',
    units: 3,
    requiresApproval: false,
    createdAt: '2026-09-04T11:00:00.000Z',
  },
];

export const INITIAL_ENROLLMENTS: Enrollment[] = [
  {
    id: 'enr-1',
    courseId: 'course-1',
    studentId: 'stu-1',
    studentName: 'Sanya Ololade Timileyin',
    matricNumber: 'FPA/CS/24/03-0108',
    status: 'APPROVED',
    enrolledAt: '2026-09-05T09:00:00.000Z',
  },
  {
    id: 'enr-2',
    courseId: 'course-1',
    studentId: 'stu-2',
    studentName: 'Adewale Segun',
    matricNumber: 'FPA/CS/24/03-0112',
    status: 'APPROVED',
    enrolledAt: '2026-09-05T09:15:00.000Z',
  },
  {
    id: 'enr-3',
    courseId: 'course-1',
    studentId: 'stu-3',
    studentName: 'Chioma Okafor',
    matricNumber: 'FPA/CS/24/03-0145',
    status: 'APPROVED',
    enrolledAt: '2026-09-05T09:30:00.000Z',
  },
  {
    id: 'enr-4',
    courseId: 'course-1',
    studentId: 'stu-4',
    studentName: 'Ibrahim Musa',
    matricNumber: 'FPA/CS/24/03-0160',
    status: 'APPROVED',
    enrolledAt: '2026-09-05T09:45:00.000Z',
  },
  {
    id: 'enr-5',
    courseId: 'course-2',
    studentId: 'stu-1',
    studentName: 'Sanya Ololade Timileyin',
    matricNumber: 'FPA/CS/24/03-0108',
    status: 'APPROVED',
    enrolledAt: '2026-09-06T10:00:00.000Z',
  },
  {
    id: 'enr-6',
    courseId: 'course-3',
    studentId: 'stu-1',
    studentName: 'Sanya Ololade Timileyin',
    matricNumber: 'FPA/CS/24/03-0108',
    status: 'PENDING',
    enrolledAt: '2026-09-20T14:00:00.000Z',
  },
];

// Current session: active for CSC 301
const now = new Date();
const activeExpiresAt = new Date(now.getTime() + 25 * 60 * 1000).toISOString();

export const INITIAL_SESSIONS: Session[] = [
  {
    id: 'sess-active-1',
    courseId: 'course-1',
    courseCode: 'CSC 301',
    courseTitle: 'Advanced Web Development & Cloud Systems',
    lecturerId: 'lec-1',
    lecturerName: 'Mrs. Abiodun',
    topic: 'Module 4: Next.js Architecture & QR Technology',
    token: 'CSC301-842',
    qrPayload: JSON.stringify({
      sessionId: 'sess-active-1',
      courseId: 'course-1',
      token: 'CSC301-842',
      v: 1,
    }),
    createdAt: new Date(now.getTime() - 5 * 60 * 1000).toISOString(),
    expiresAt: activeExpiresAt,
    durationMinutes: 30,
    isActive: true,
  },
  {
    id: 'sess-past-1',
    courseId: 'course-1',
    courseCode: 'CSC 301',
    courseTitle: 'Advanced Web Development & Cloud Systems',
    lecturerId: 'lec-1',
    lecturerName: 'Mrs. Abiodun',
    topic: 'Module 3: React Server Components & API Routes',
    token: 'CSC301-209',
    qrPayload: JSON.stringify({
      sessionId: 'sess-past-1',
      courseId: 'course-1',
      token: 'CSC301-209',
      v: 1,
    }),
    createdAt: '2026-09-22T09:00:00.000Z',
    expiresAt: '2026-09-22T09:30:00.000Z',
    durationMinutes: 30,
    isActive: false,
  },
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  {
    id: 'att-1',
    sessionId: 'sess-past-1',
    courseId: 'course-1',
    courseCode: 'CSC 301',
    courseTitle: 'Advanced Web Development & Cloud Systems',
    studentId: 'stu-1',
    studentName: 'Sanya Ololade Timileyin',
    matricNumber: 'FPA/CS/24/03-0108',
    markedAt: '2026-09-22T09:08:14.000Z',
    method: 'QR_SCAN',
    status: 'PRESENT',
    deviceInfo: 'Chrome Mobile / Android',
  },
  {
    id: 'att-2',
    sessionId: 'sess-past-1',
    courseId: 'course-1',
    courseCode: 'CSC 301',
    courseTitle: 'Advanced Web Development & Cloud Systems',
    studentId: 'stu-2',
    studentName: 'Adewale Segun',
    matricNumber: 'FPA/CS/24/03-0112',
    markedAt: '2026-09-22T09:11:02.000Z',
    method: 'QR_SCAN',
    status: 'PRESENT',
    deviceInfo: 'Safari Mobile / iPhone',
  },
  {
    id: 'att-3',
    sessionId: 'sess-past-1',
    courseId: 'course-1',
    courseCode: 'CSC 301',
    courseTitle: 'Advanced Web Development & Cloud Systems',
    studentId: 'stu-3',
    studentName: 'Chioma Okafor',
    matricNumber: 'FPA/CS/24/03-0145',
    markedAt: '2026-09-22T09:14:48.000Z',
    method: 'SESSION_CODE',
    status: 'PRESENT',
    deviceInfo: 'Edge / Windows',
  },
  {
    id: 'att-4',
    sessionId: 'sess-active-1',
    courseId: 'course-1',
    courseCode: 'CSC 301',
    courseTitle: 'Advanced Web Development & Cloud Systems',
    studentId: 'stu-2',
    studentName: 'Adewale Segun',
    matricNumber: 'FPA/CS/24/03-0112',
    markedAt: new Date(now.getTime() - 3 * 60 * 1000).toISOString(),
    method: 'QR_SCAN',
    status: 'PRESENT',
    deviceInfo: 'Safari Mobile / iPhone',
  },
];
